export const ROLES = {
  RESCATISTA_CIVIL: 'RESCATISTA_CIVIL',
  PROTECCION_CIVIL: 'PROTECCION_CIVIL',
  PERSONAL_MEDICO: 'PERSONAL_MEDICO',
  CONSEJERO_CPNNA: 'CONSEJERO_CPNNA',
  ADMINISTRADOR: 'ADMINISTRADOR',
};

export const ACCOUNT_STATUS = {
  PENDIENTE: 'PENDIENTE',
  ACTIVO: 'ACTIVO',
  SUSPENDIDO: 'SUSPENDIDO',
  RECHAZADO: 'RECHAZADO',
};

/** Roles de función operativa de auxilio (pueden solicitar alta pública). */
export const OPERATIONAL_ROLES = [
  ROLES.RESCATISTA_CIVIL,
  ROLES.PROTECCION_CIVIL,
  ROLES.PERSONAL_MEDICO,
];

/** Roles con competencia de disposición jurídica (solo alta por admin). */
export const AUTHORITY_ROLES = [ROLES.CONSEJERO_CPNNA, ROLES.ADMINISTRADOR];

/** Cierre legal y entrega oficial: competencia exclusiva CPNNA (LOPNNA arts. 158–160). */
export const ROLES_CIERRE_LEGAL = [ROLES.CONSEJERO_CPNNA, ROLES.ADMINISTRADOR];

export const NNA_STATUS = {
  EN_SITIO: 'EN_SITIO',
  EN_TRANSITO: 'EN_TRANSITO',
  RESGUARDADO: 'RESGUARDADO',
  ENTREGADO_AUTORIDAD: 'ENTREGADO_AUTORIDAD',
};

export const TIMELINE_EVENT_TYPES = {
  REGISTRO_INICIAL: 'REGISTRO_INICIAL',
  TRASLADO: 'TRASLADO',
  ATENCION_MEDICA: 'ATENCION_MEDICA',
  INGRESO_REFUGIO: 'INGRESO_REFUGIO',
  ENTREGA_OFICIAL: 'ENTREGA_OFICIAL',
};

export const ESTADO_SALUD = {
  ESTABLE: 'ESTABLE',
  REQUIERE_ATENCION_URGENTE: 'REQUIERE_ATENCION_URGENTE',
  CON_LESIONES_VISIBLES: 'CON_LESIONES_VISIBLES',
};

export const STATUS_BY_EVENT = {
  TRASLADO: NNA_STATUS.EN_TRANSITO,
  INGRESO_REFUGIO: NNA_STATUS.RESGUARDADO,
  ENTREGA_OFICIAL: NNA_STATUS.ENTREGADO_AUTORIDAD,
};

export const INSTITUTION_TYPES = {
  PROTECCION_CIVIL: 'PROTECCION_CIVIL',
  SALUD: 'SALUD',
  CPNNA: 'CPNNA',
  RESCATE_VOLUNTARIO: 'RESCATE_VOLUNTARIO',
  GOBIERNO: 'GOBIERNO',
};

export const ENTIDAD_ATENCION_TYPES = {
  REFUGIO_OFICIAL: 'REFUGIO_OFICIAL',
  HOSPITAL: 'HOSPITAL',
  CENTRO_ATENCION: 'CENTRO_ATENCION',
  ALBERGUE_INSTITUCIONAL: 'ALBERGUE_INSTITUCIONAL',
};

/** Eventos de timeline que exigen destino institucional autorizado. */
export const TIMELINE_EVENTS_REQUIRING_ENTIDAD = [
  TIMELINE_EVENT_TYPES.TRASLADO,
  TIMELINE_EVENT_TYPES.INGRESO_REFUGIO,
];

/** Permisos por tipo de evento en timeline (LOPNNA / protocolo). */
export const TIMELINE_EVENT_PERMISSIONS = {
  [TIMELINE_EVENT_TYPES.REGISTRO_INICIAL]: [
    ROLES.RESCATISTA_CIVIL,
    ROLES.PROTECCION_CIVIL,
    ROLES.PERSONAL_MEDICO,
    ROLES.ADMINISTRADOR,
  ],
  [TIMELINE_EVENT_TYPES.TRASLADO]: [
    ROLES.RESCATISTA_CIVIL,
    ROLES.PROTECCION_CIVIL,
    ROLES.PERSONAL_MEDICO,
    ROLES.ADMINISTRADOR,
  ],
  [TIMELINE_EVENT_TYPES.ATENCION_MEDICA]: [
    ROLES.PERSONAL_MEDICO,
    ROLES.PROTECCION_CIVIL,
    ROLES.ADMINISTRADOR,
  ],
  [TIMELINE_EVENT_TYPES.INGRESO_REFUGIO]: [
    ROLES.PROTECCION_CIVIL,
    ROLES.CONSEJERO_CPNNA,
    ROLES.ADMINISTRADOR,
  ],
  [TIMELINE_EVENT_TYPES.ENTREGA_OFICIAL]: [ROLES.CONSEJERO_CPNNA, ROLES.ADMINISTRADOR],
};

/** Roles que pueden registrar NNA y operar en campo. */
export const ROLES_REGISTRO_NNA = [
  ROLES.RESCATISTA_CIVIL,
  ROLES.PROTECCION_CIVIL,
  ROLES.PERSONAL_MEDICO,
  ROLES.ADMINISTRADOR,
];

export const AUDIT_ACTIONS = {
  USUARIO_SOLICITUD: 'USUARIO_SOLICITUD',
  USUARIO_APROBADO: 'USUARIO_APROBADO',
  USUARIO_RECHAZADO: 'USUARIO_RECHAZADO',
  USUARIO_REGISTRO_ADMIN: 'USUARIO_REGISTRO_ADMIN',
  NNA_REGISTRADO: 'NNA_REGISTRADO',
  NNA_TIMELINE: 'NNA_TIMELINE',
  NNA_CIERRE_LEGAL: 'NNA_CIERRE_LEGAL',
  NNA_UBICACION: 'NNA_UBICACION',
};
